# Generated by Django 3.1.4 on 2021-01-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('color', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.color')),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.photo')),
                ('related', models.ManyToManyField(related_name='_product_related_+', to='core.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.size')),
            ],
        ),
    ]
