# Generated by Django 3.1.4 on 2021-01-02 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
