# Generated by Django 3.1.4 on 2021-01-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210102_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(null=True, related_name='_product_related_+', to='core.Product'),
        ),
    ]
