# Generated by Django 3.1.5 on 2021-01-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210107_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related',
            field=models.ManyToManyField(blank=True, limit_choices_to={'title': models.CharField(max_length=100)}, related_name='_product_related_+', to='core.Product'),
        ),
    ]
