# Generated by Django 3.1.4 on 2021-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210102_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.ManyToManyField(to='core.Photo'),
        ),
    ]
